spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/dev?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
  redis:
    host: localhost
    port: 6379
server:
  port: 8085